# Generated by Django 4.2.3 on 2023-08-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_rename_stars_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='movies_count',
            field=models.IntegerField(default=0),
        ),
    ]
