# Generated by Django 4.2.3 on 2023-08-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_director_movies_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movies_count',
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movie_app.director'),
        ),
    ]
